skip_local_validator = false

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ned_program = "8azx4HdoXQ8VQFn5QWaoBU2PMg3RX99Z2agrWyMbX5Wh"

[programs.localnet]
ned_program = "8azx4HdoXQ8VQFn5QWaoBU2PMg3RX99Z2agrWyMbX5Wh"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/ned-program/Cargo.toml -- --nocapture"

[hooks]
