import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useAuth } from '@/services/auth';
import { getSolanaBalance, getUsdcTokenBalance } from '@/services/solana';
import { calculateFee, calculateMinimumReceived, getTokens, quoteMintForAsset, searchTokens, Slippage, useSwapQuote, JupiterToken } from '@/services/jupiter';
import { saveDemoSwap } from '@/services/storage';
import { onbColors, onbFonts } from '@/components/onboarding/theme';

type Stage = 'amount' | 'tokens' | 'review' | 'result';
const decimals = (asset: 'SOL' | 'USDC') => asset === 'SOL' ? 9 : 6;
const pretty = (raw: string, asset: 'SOL' | 'USDC') => `${(Number(raw) / 10 ** decimals(asset)).toFixed(asset === 'SOL' ? 6 : 2)} ${asset}`;

export default function SwapScreen() {
  const router = useRouter(); const { walletAddress } = useAuth();
  const [from, setFrom] = useState<'SOL' | 'USDC'>('SOL'); const to = from === 'SOL' ? 'USDC' : 'SOL';
  const [amount, setAmount] = useState(''); const [slippage, setSlippage] = useState<Slippage>('auto'); const [stage, setStage] = useState<Stage>('amount');
  const [balance, setBalance] = useState(0); const [search, setSearch] = useState(''); const [tokens, setTokens] = useState<JupiterToken[]>([]); const [result, setResult] = useState<'success' | 'failed'>('success');
  const [selectedToken, setSelectedToken] = useState<JupiterToken | null>(null);
  const inputMint = quoteMintForAsset(from); const outputMint = quoteMintForAsset(to);
  const rawAmount = amount ? String(Math.floor(Number(amount) * 10 ** decimals(from))) : '';
  const quoteState = useSwapQuote(inputMint, outputMint, rawAmount, slippage);
  useEffect(() => { if (!walletAddress) return; void Promise.all([getSolanaBalance(walletAddress), getUsdcTokenBalance(walletAddress)]).then(([sol, usdc]) => setBalance(from === 'SOL' ? sol : usdc)); }, [walletAddress, from]);
  useEffect(() => { if (stage !== 'tokens') return; void (search ? searchTokens(search) : getTokens('verified')).then(setTokens).catch(() => setTokens([])); }, [stage, search]);
  const fee = quoteState.quote ? calculateFee(BigInt(quoteState.quote.outAmount)) : 0n;
  const minimum = quoteState.quote ? calculateMinimumReceived(quoteState.quote) : 0n;
  const notEnough = Number(amount || 0) > balance;
  const route = quoteState.quote?.routePlan?.map((r) => r.swapInfo?.label).filter(Boolean).join(' → ') || quoteState.quote?.router || 'Jupiter';
  const flip = () => { setFrom(to); setAmount(''); setStage('amount'); };
  const confirm = async () => { if (!quoteState.quote || quoteState.isStale) { setResult('failed'); setStage('result'); return; } await saveDemoSwap({ type: 'swap', title: `Demo swap ${from} → ${to}`, amount: pretty(rawAmount, from), received: pretty(quoteState.quote.outAmount, to), time: new Date().toISOString() }, walletAddress); setResult('success'); setStage('result'); };
  if (stage === 'result') return <Screen><View style={styles.result}><Text style={styles.emoji}>{result === 'success' ? '✓' : '!'}</Text><Text style={styles.title}>{result === 'success' ? 'Swap complete' : "Swap didn't go through"}</Text><Text style={styles.muted}>Demo mode · real price, no real funds moved</Text>{result === 'failed' ? <Text style={styles.warning}>The price moved more than your limit, so nothing was swapped.</Text> : null}<Button title={result === 'success' ? 'Done' : 'Try again'} onPress={() => result === 'success' ? router.back() : setStage('review')} /><Button title="Swap again" secondary onPress={() => { setAmount(''); setStage('amount'); }} /></View></Screen>;
  if (stage === 'tokens') return <Screen><Header title="Pick a token" onBack={() => setStage('amount')} /><TextInput value={search} onChangeText={setSearch} placeholder="Search symbol, name or mint" placeholderTextColor={onbColors.textSubtle} style={styles.input} />{selectedToken && !selectedToken.isVerified ? <View style={styles.unverified}><Text style={styles.warning}>UNVERIFIED TOKEN</Text><Text style={styles.muted}>Only use a token you trust.</Text><Button title="I understand, use this token" onPress={() => setStage('amount')} /></View> : null}<ScrollView>{tokens.slice(0, 30).map((token) => <Pressable key={token.id} style={styles.token} onPress={() => { setSelectedToken(token); setStage('amount'); }}><View><Text style={styles.tokenName}>{token.symbol || token.name || token.id.slice(0, 8)}</Text><Text style={styles.muted}>{token.name || token.id}</Text></View><Text style={token.isVerified ? styles.verified : styles.warning}>{token.isVerified ? 'VERIFIED' : 'UNVERIFIED'}</Text></Pressable>)}</ScrollView><Pressable onPress={() => {}}><Text style={styles.link}>Looking for stocks like AAPLx?</Text></Pressable></Screen>;
  if (stage === 'review') return <Screen><Header title="Review swap" onBack={() => setStage('amount')} /><View style={styles.card}><Text style={styles.label}>You pay</Text><Text style={styles.big}>{amount} {from}</Text><Text style={styles.label}>You get</Text><Text style={styles.big}>{quoteState.quote ? pretty(quoteState.quote.outAmount, to) : '—'}</Text></View><Row label="Rate" value={quoteState.quote ? `1 ${from} ≈ ${(Number(quoteState.quote.outAmount) / 10 ** decimals(to) / (Number(rawAmount) / 10 ** decimals(from))).toFixed(4)} ${to}` : '—'} /><Row label="N.E.D fee (0.25%)" value={`~${fee.toString()} raw units`} /><Row label="Network fee" value="Demo — not broadcast" /><Row label="Price impact" value={`${quoteState.quote?.priceImpact ?? 0}%`} /><Row label="Minimum you get" value={quoteState.quote ? pretty(minimum.toString(), to) : '—'} /><Row label="Route" value={route} />{quoteState.isStale ? <Text style={styles.warning}>Price updated · Accept a fresh quote before confirming.</Text> : null}<Button title={quoteState.isStale ? 'Accept new price' : 'Slide to confirm'} onPress={() => quoteState.isStale ? void quoteState.refresh() : void confirm()} disabled={quoteState.isLoading} /></Screen>;
  return <Screen><Header title="Swap" onBack={() => router.back()} /><Text style={styles.label}>You pay</Text><View style={styles.card}><TextInput keyboardType="decimal-pad" value={amount} onChangeText={setAmount} placeholder="0.00" placeholderTextColor={onbColors.textSubtle} style={styles.amount} /><Pressable onPress={() => setStage('tokens')}><Text style={styles.pill}>{selectedToken?.symbol || from} <Feather name="chevron-down" size={14} color="white" /></Text></Pressable><Text style={styles.muted}>Balance {balance.toFixed(4)} {from}</Text><View style={styles.chips}><Pressable onPress={() => setAmount((balance * 0.5).toFixed(6))}><Text style={styles.chip}>50%</Text></Pressable><Pressable onPress={() => setAmount(balance.toFixed(6))}><Text style={styles.chip}>Max</Text></Pressable></View></View><Pressable style={styles.flip} onPress={flip}><Feather name="repeat" size={20} color="white" /></Pressable><Text style={styles.label}>You get</Text><View style={styles.card}><Text style={styles.big}>{quoteState.quote ? pretty(quoteState.quote.outAmount, to) : '—'}</Text><Text style={styles.muted}>{quoteState.isLoading ? 'Updating quote…' : quoteState.error || `Updates in ${quoteState.secondsRemaining}s`}</Text></View><View style={styles.slippage}>{(['auto', 0.5, 1, 3] as Slippage[]).map((value) => <Pressable key={String(value)} onPress={() => setSlippage(value)}><Text style={[styles.chip, slippage === value && styles.selected]}>{value === 'auto' ? 'Auto' : `${value}%`}</Text></Pressable>)}</View>{slippage === 3 ? <Text style={styles.warning}>3% slippage may result in a worse price.</Text> : null}<Text style={styles.muted}>N.E.D fee 0.25% · {quoteState.quote ? `$${((Number(quoteState.quote.outUsdValue || 0) * 0.0025) || 0).toFixed(2)}` : '$0.00'} · Network fee paid by you on Devnet</Text><Button title={notEnough ? `Not enough ${from}` : !amount ? 'Enter an amount' : 'Review swap'} disabled={notEnough || !amount || quoteState.isLoading} onPress={() => setStage('review')} /></Screen>;
}

function Screen({ children }: { children: React.ReactNode }) { return <LinearGradient colors={['#110822', '#0D0618', '#06060E']} style={styles.fill}><SafeAreaView style={styles.safe}>{children}</SafeAreaView></LinearGradient>; }
function Header({ title, onBack }: { title: string; onBack: () => void }) { return <View style={styles.header}><Pressable onPress={onBack}><Feather name="arrow-left" size={24} color="white" /></Pressable><Text style={styles.title}>{title}</Text><View style={{ width: 24 }} /></View>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.muted}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
function Button({ title, onPress, disabled, secondary }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.secondary, disabled && styles.disabled]}><Text style={styles.buttonText}>{title}</Text></Pressable>; }
const styles = StyleSheet.create({ fill: { flex: 1 }, safe: { flex: 1, padding: 20, maxWidth: 520, width: '100%', alignSelf: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }, title: { color: 'white', fontFamily: onbFonts.heading, fontSize: 22 }, label: { color: onbColors.textMuted, fontFamily: onbFonts.bodyMedium, marginBottom: 8 }, card: { backgroundColor: onbColors.surface, borderColor: onbColors.border, borderWidth: 1, borderRadius: 18, padding: 18, marginBottom: 12 }, amount: { color: 'white', fontFamily: onbFonts.mono, fontSize: 32, flex: 1 }, big: { color: 'white', fontFamily: onbFonts.mono, fontSize: 24, marginBottom: 12 }, pill: { color: 'white', fontFamily: onbFonts.bodySemi, fontSize: 16 }, muted: { color: onbColors.textMuted, fontFamily: onbFonts.body, fontSize: 13 }, chips: { flexDirection: 'row', gap: 8, marginTop: 14 }, chip: { color: onbColors.textMuted, borderColor: onbColors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 7, paddingHorizontal: 12 }, selected: { backgroundColor: onbColors.purple, color: 'white' }, flip: { alignSelf: 'center', padding: 10, borderRadius: 20, backgroundColor: onbColors.purple, marginVertical: 2 }, slippage: { flexDirection: 'row', gap: 8, marginVertical: 14 }, button: { backgroundColor: onbColors.purple, borderRadius: 16, padding: 17, alignItems: 'center', marginTop: 20 }, secondary: { backgroundColor: 'transparent', borderWidth: 1, borderColor: onbColors.border }, disabled: { opacity: 0.45 }, buttonText: { color: 'white', fontFamily: onbFonts.bodyBold, fontSize: 16 }, input: { color: 'white', borderColor: onbColors.border, borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 12 }, token: { flexDirection: 'row', justifyContent: 'space-between', padding: 16, borderBottomColor: onbColors.border, borderBottomWidth: 1 }, tokenName: { color: 'white', fontFamily: onbFonts.bodySemi, fontSize: 16 }, verified: { color: onbColors.successText, fontFamily: onbFonts.bodyBold, fontSize: 11 }, warning: { color: onbColors.warning, fontFamily: onbFonts.bodyMedium, marginVertical: 12 }, unverified: { borderColor: onbColors.warning, borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 10 }, link: { color: onbColors.lavender, textAlign: 'center', marginTop: 12 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 11, borderBottomColor: onbColors.border, borderBottomWidth: 1 }, rowValue: { color: 'white', maxWidth: '62%', textAlign: 'right', fontFamily: onbFonts.bodyMedium }, result: { alignItems: 'center', justifyContent: 'center', flex: 1 }, emoji: { color: onbColors.successText, fontSize: 60, fontFamily: onbFonts.heading, marginBottom: 15 } });
