import React, { useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import Svg, { Polygon, Polyline } from 'react-native-svg';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { useAuth } from '@/services/auth';
import { getUsdcTokenBalance } from '@/services/solana';
import { getXStocks, getGeckoOhlcv, isUsMarketOpen, sortXStocks, XStock, XStockSort } from '@/services/xstocks';
import { getDemoLedger, recordDemoBuy, recordDemoSell, type DemoLedger } from '@/services/demoLedger';
import { getOrder, MAINNET_USDC_MINT } from '@/services/jupiter';
import { onbColors, onbFonts } from '@/components/onboarding/theme';
import { amountNumber, sanitizeAmountInput } from '@/utils/amountInput';

type Stage = 'list' | 'detail' | 'trade' | 'review' | 'success' | 'failed';
export default function XStocksScreen() {
  const router = useRouter(); const { walletAddress } = useAuth(); const [stocks, setStocks] = useState<XStock[]>([]); const [stock, setStock] = useState<XStock | null>(null); const [stage, setStage] = useState<Stage>('list'); const [side, setSide] = useState<'buy' | 'sell'>('buy'); const [sort, setSort] = useState<XStockSort>('movers'); const [query, setQuery] = useState(''); const [amount, setAmount] = useState(''); const [range, setRange] = useState<'1' | '7' | '30' | '180'>('1'); const [chart, setChart] = useState<number[]>([]); const [ledger, setLedger] = useState<DemoLedger>({ cashUsdc: 0, holdings: [], trades: [] }); const [baseCash, setBaseCash] = useState(0); const [risk, setRisk] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void getXStocks().then(setStocks).catch((e) => setError(e.message)); }, []);
  useEffect(() => { if (walletAddress) void getDemoLedger(walletAddress).then(setLedger); }, [walletAddress, stage]);
  useEffect(() => { if (walletAddress) void getUsdcTokenBalance(walletAddress).then(setBaseCash); }, [walletAddress]);
  useEffect(() => { if (!stock) return; void getGeckoOhlcv(stock.id, range).then((rows) => setChart(rows.map((row) => row[4]))).catch(() => setChart([])); }, [stock, range]);
  const visible = useMemo(() => sortXStocks(stocks.filter((item) => !query || item.symbol.toLowerCase().includes(query.toLowerCase()) || item.name?.toLowerCase().includes(query.toLowerCase())), sort), [stocks, query, sort]);
  const holding = stock ? ledger.holdings.find((item) => item.mint === stock.id) : undefined;
  async function reviewTrade() { if (!walletAddress || !stock) return; try { const usd = amountNumber(amount); if (side === 'buy') { const quote = await getOrder(MAINNET_USDC_MINT, stock.id, Math.floor(usd * 1e6), 'auto'); if (!quote.outAmount || usd > baseCash + ledger.cashUsdc) throw new Error('Not enough USDC'); } else if (!holding || usd <= 0 || usd > holding.quantity) throw new Error('Not enough demo shares'); setStage('review'); } catch (e) { setError(e instanceof Error ? e.message : 'Quote unavailable'); } }
  async function confirmTrade() { if (!walletAddress || !stock) return; try { const usd = amountNumber(amount); if (side === 'buy') { const quote = await getOrder(MAINNET_USDC_MINT, stock.id, Math.floor(usd * 1e6), 'auto'); if (!quote.outAmount) throw new Error('No route found'); await recordDemoBuy(walletAddress, { mint: stock.id, symbol: stock.symbol, usd, price: stock.usdPrice || 0, }); } else { const quantity = usd; const quote = await getOrder(stock.id, MAINNET_USDC_MINT, Math.floor(quantity * 10 ** stock.decimals), 'auto'); if (!quote.outAmount) throw new Error('No route found'); await recordDemoSell(walletAddress, { mint: stock.id, symbol: stock.symbol, quantity, price: stock.usdPrice || 0 }); } setStage('success'); } catch (e) { setError(e instanceof Error ? e.message : 'Demo trade failed'); setStage('failed'); } }
  if (stage === 'success' || stage === 'failed') return <Screen><View style={styles.center}><Text style={styles.emoji}>{stage === 'success' ? '✓' : '!'}</Text><Text style={styles.title}>{stage === 'success' ? (side === 'buy' ? 'Investment added' : 'Sale complete') : 'Trade failed'}</Text><Text style={styles.muted}>Demo mode · real price, no real funds moved</Text>{error ? <Text style={styles.warning}>{error}</Text> : null}<Button title="Done" onPress={() => setStage('list')} /></View></Screen>;
  if (stage === 'review') return <Screen><Header title="Review" onBack={() => setStage('trade')} /><View style={styles.card}><Row label="Side" value={side.toUpperCase()} /><Row label="Asset" value={stock?.symbol || ''} /><Row label={side === 'buy' ? 'You pay' : 'You sell'} value={`${amount} ${side === 'buy' ? 'USDC' : stock?.symbol}`} /><Row label="N.E.D fee" value="0.25%" /><Row label="Network fee" value="Demo — not broadcast" /></View>{!isUsMarketOpen() ? <Text style={styles.warning}>US market is closed; on-chain price may differ from Friday close.</Text> : null}{side === 'buy' ? <Pressable onPress={() => setRisk(!risk)}><Text style={styles.muted}>{risk ? '☑' : '☐'} This tracks the share price but is not an Apple share or a claim on the company.</Text></Pressable> : null}<Button title="Confirm demo trade" disabled={side === 'buy' && !risk} onPress={() => void confirmTrade()} /></Screen>;
  if (stage === 'trade') return <Screen><Header title={`${side === 'buy' ? 'Buy' : 'Sell'} ${stock?.symbol}`} onBack={() => setStage('detail')} /><Text style={styles.label}>{side === 'buy' ? 'USD amount' : 'Shares to sell'}</Text><TextInput value={amount} onChangeText={(value) => setAmount(sanitizeAmountInput(value, 6).display)} keyboardType="decimal-pad" placeholder={side === 'buy' ? '50' : '0'} placeholderTextColor={onbColors.textSubtle} style={styles.input} /><View style={styles.chips}>{(side === 'buy' ? ['10', '50', '100'] : ['25%', '50%', '75%', '100%']).map((value) => <Pressable key={value} onPress={() => setAmount(side === 'buy' ? value : String(((holding?.quantity || 0) * Number(value.replace('%', '')) / 100).toFixed(6)))}><Text style={styles.chip}>{side === 'buy' ? `$${value}` : value}</Text></Pressable>)}</View><Text style={styles.muted}>{side === 'buy' ? 'Cash balance · USDC' : `Position ${holding?.quantity?.toFixed(6) || '0'} ${stock?.symbol}`}</Text>{error ? <Text style={styles.warning}>{error}</Text> : null}<Button title="Review" disabled={amountNumber(amount) <= 0} onPress={() => void reviewTrade()} /></Screen>;
  if (stage === 'detail' && stock) return <Screen><Header title={stock.symbol} onBack={() => setStage('list')} /><Text style={styles.price}>${(stock.usdPrice || 0).toFixed(4)}</Text><Text style={stock.priceChange24h >= 0 ? styles.positive : styles.warning}>{stock.priceChange24h.toFixed(2)}% 24h</Text>{!isUsMarketOpen() ? <Text style={styles.warning}>US market closed · on-chain price</Text> : null}<View style={styles.ranges}>{(['1', '7', '30', '180'] as const).map((value) => <Pressable key={value} onPress={() => setRange(value)}><Text style={[styles.chip, range === value && styles.selected]}>{value === '1' ? '1D' : value === '7' ? '1W' : value === '30' ? '1M' : '6M'}</Text></Pressable>)}</View><Chart values={chart} /><Text style={styles.muted}>Chart by GeckoTerminal</Text><Row label="Your position" value={`${holding?.quantity?.toFixed(6) || '0'} ${stock.symbol}`} /><Row label="Liquidity" value={`$${(stock.liquidity || 0).toLocaleString()}`} /><Row label="Holders" value={String(stock.holderCount || '—')} /><Text style={styles.muted}>What is an xStock? A token that tracks a public share price on-chain; it is not the underlying security.</Text><View style={styles.actions}><Button title="Sell" secondary onPress={() => { setSide('sell'); setAmount(''); setStage('trade'); }} /><Button title="Buy" onPress={() => { setSide('buy'); setAmount(''); setStage('trade'); }} /></View></Screen>;
  return <Screen><Header title="xStocks" onBack={() => router.back()} /><Text style={styles.muted}>{isUsMarketOpen() ? 'US market open' : 'US market closed'}</Text><View style={styles.card}><Text style={styles.label}>Your investments</Text><Text style={styles.price}>${ledger.holdings.reduce((sum, h) => sum + h.quantity * (stocks.find((s) => s.id === h.mint)?.usdPrice || 0), 0).toFixed(2)}</Text><Text style={styles.muted}>Demo balance · {ledger.holdings.length} positions</Text></View><TextInput value={query} onChangeText={setQuery} placeholder="Search stocks & ETFs" placeholderTextColor={onbColors.textSubtle} style={styles.input} /><View style={styles.ranges}>{(['movers', 'traded', 'az'] as XStockSort[]).map((value) => <Pressable key={value} onPress={() => setSort(value)}><Text style={[styles.chip, sort === value && styles.selected]}>{value === 'movers' ? 'Top movers' : value === 'traded' ? 'Most traded' : 'A–Z'}</Text></Pressable>)}</View><ScrollView>{visible.map((item) => <Pressable key={item.id} style={styles.stock} onPress={() => { setStock(item); setStage('detail'); }}><View><Text style={styles.stockSymbol}>{item.symbol}</Text><Text style={styles.muted}>{item.name || 'xStock'}</Text></View><View><Text style={styles.stockPrice}>${(item.usdPrice || 0).toFixed(2)}</Text><Text style={item.priceChange24h >= 0 ? styles.positive : styles.warning}>{item.priceChange24h.toFixed(2)}%</Text></View></Pressable>)}</ScrollView></Screen>;
}
function Screen({ children }: { children: React.ReactNode }) { return <LinearGradient colors={['#110822', '#0D0618', '#06060E']} style={styles.fill}><SafeAreaView style={styles.safe}>{children}</SafeAreaView></LinearGradient>; }
function Header({ title, onBack }: { title: string; onBack: () => void }) { return <View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>{title}</Text><View style={{ width: 20 }} /></View>; }
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.muted}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
function Button({ title, onPress, disabled, secondary }: { title: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.secondary, disabled && styles.disabled]}><Text style={styles.buttonText}>{title}</Text></Pressable>; }
function Chart({ values }: { values: number[] }) { if (values.length < 2) return <View style={styles.chart}><Text style={styles.muted}>Chart data unavailable</Text></View>; const min = Math.min(...values); const max = Math.max(...values); const points = values.map((value, index) => `${(index / (values.length - 1)) * 320},${100 - ((value - min) / (max - min || 1)) * 90}`).join(' '); return <Svg width="100%" height="120" viewBox="0 0 320 110"><Polygon points={`0,110 ${points} 320,110`} fill="rgba(155,79,222,0.18)" /><Polyline points={points} fill="none" stroke="#B87AED" strokeWidth="3" /></Svg>; }
const styles = StyleSheet.create({ fill: { flex: 1 }, safe: { flex: 1, padding: 20, maxWidth: 520, width: '100%', alignSelf: 'center' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }, back: { color: 'white', fontSize: 32 }, title: { color: 'white', fontFamily: onbFonts.heading, fontSize: 22 }, label: { color: onbColors.textMuted, fontFamily: onbFonts.bodyMedium, marginBottom: 8 }, muted: { color: onbColors.textMuted, fontFamily: onbFonts.body, fontSize: 13, marginVertical: 5 }, card: { backgroundColor: onbColors.surface, borderColor: onbColors.border, borderWidth: 1, borderRadius: 16, padding: 16, marginVertical: 12 }, price: { color: 'white', fontFamily: onbFonts.mono, fontSize: 30, marginVertical: 8 }, input: { color: 'white', borderColor: onbColors.border, borderWidth: 1, borderRadius: 12, padding: 14, marginVertical: 10 }, ranges: { flexDirection: 'row', gap: 8, marginVertical: 10 }, chips: { flexDirection: 'row', gap: 8, marginVertical: 10 }, chip: { color: onbColors.textMuted, borderColor: onbColors.border, borderWidth: 1, borderRadius: 8, padding: 8 }, selected: { backgroundColor: onbColors.purple, color: 'white' }, stock: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 16, borderBottomColor: onbColors.border, borderBottomWidth: 1 }, stockSymbol: { color: 'white', fontFamily: onbFonts.bodyBold, fontSize: 17 }, stockPrice: { color: 'white', fontFamily: onbFonts.mono, textAlign: 'right' }, positive: { color: onbColors.successText, fontFamily: onbFonts.bodyMedium }, warning: { color: onbColors.warning, fontFamily: onbFonts.bodyMedium, marginVertical: 8 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomColor: onbColors.border, borderBottomWidth: 1 }, rowValue: { color: 'white', fontFamily: onbFonts.bodyMedium, maxWidth: '65%', textAlign: 'right' }, button: { backgroundColor: onbColors.purple, borderRadius: 15, padding: 16, alignItems: 'center', marginTop: 18, flex: 1 }, secondary: { backgroundColor: 'transparent', borderColor: onbColors.border, borderWidth: 1 }, disabled: { opacity: 0.4 }, buttonText: { color: 'white', fontFamily: onbFonts.bodyBold }, actions: { flexDirection: 'row', gap: 10 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, emoji: { color: onbColors.successText, fontSize: 60 }, chart: { height: 120, justifyContent: 'center', alignItems: 'center' } });
